# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('name', models.CharField(default='Anonymus', max_length=200, primary_key=True, serialize=False)),
                ('profileUrl', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='prezi',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prezi',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='prezi',
            name='creator',
            field=models.ForeignKey(default='Anonymus', on_delete=django.db.models.deletion.CASCADE, to='processor.Creator'),
        ),
    ]
