# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0003_auto_20160403_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='profileUrl',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prezi',
            name='thumbnail',
            field=models.SlugField(max_length=200),
        ),
    ]
