# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0007_auto_20160403_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prezi',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
